// File generated by hadoop record compiler. Do not edit.
/**
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package org.lab.mars.onem2m.proto;

import org.lab.mars.onem2m.jute.BinaryInputArchive;
import org.lab.mars.onem2m.jute.BinaryOutputArchive;
import org.lab.mars.onem2m.jute.CsvOutputArchive;
import org.lab.mars.onem2m.jute.InputArchive;
import org.lab.mars.onem2m.jute.OutputArchive;
import org.lab.mars.onem2m.jute.Record;
public class GetACLResponse implements Record {
  private java.util.List<org.lab.mars.onem2m.data.ACL> acl;
  private org.lab.mars.onem2m.data.Stat stat;
  public GetACLResponse() {
  }
  public GetACLResponse(
        java.util.List<org.lab.mars.onem2m.data.ACL> acl,
        org.lab.mars.onem2m.data.Stat stat) {
    this.acl=acl;
    this.stat=stat;
  }
  public java.util.List<org.lab.mars.onem2m.data.ACL> getAcl() {
    return acl;
  }
  public void setAcl(java.util.List<org.lab.mars.onem2m.data.ACL> m_) {
    acl=m_;
  }
  public org.lab.mars.onem2m.data.Stat getStat() {
    return stat;
  }
  public void setStat(org.lab.mars.onem2m.data.Stat m_) {
    stat=m_;
  }
  public void serialize(OutputArchive a_, String tag) throws java.io.IOException {
    a_.startRecord(this,tag);
    a_.writeRecord(stat,"stat");
    a_.endRecord(this,tag);
  }
  public void deserialize(InputArchive a_, String tag) throws java.io.IOException {
    a_.startRecord(tag);
    stat= new org.lab.mars.onem2m.data.Stat();
    a_.readRecord(stat,"stat");
    a_.endRecord(tag);
}
  public String toString() {
    try {
      java.io.ByteArrayOutputStream s =
        new java.io.ByteArrayOutputStream();
      CsvOutputArchive a_ = 
        new CsvOutputArchive(s);
      a_.startRecord(this,"");
    a_.writeRecord(stat,"stat");
      a_.endRecord(this,"");
      return new String(s.toByteArray(), "UTF-8");
    } catch (Throwable ex) {
      ex.printStackTrace();
    }
    return "ERROR";
  }
  public void write(java.io.DataOutput out) throws java.io.IOException {
    BinaryOutputArchive archive = new BinaryOutputArchive(out);
    serialize(archive, "");
  }
  public void readFields(java.io.DataInput in) throws java.io.IOException {
    BinaryInputArchive archive = new BinaryInputArchive(in);
    deserialize(archive, "");
  }
  public int compareTo (Object peer_) throws ClassCastException {
    throw new UnsupportedOperationException("comparing GetACLResponse is unimplemented");
  }
  public boolean equals(Object peer_) {
    if (!(peer_ instanceof GetACLResponse)) {
      return false;
    }
    if (peer_ == this) {
      return true;
    }
    GetACLResponse peer = (GetACLResponse) peer_;
    boolean ret = false;
    ret = acl.equals(peer.acl);
    if (!ret) return ret;
    ret = stat.equals(peer.stat);
    if (!ret) return ret;
     return ret;
  }
  public int hashCode() {
    int result = 17;
    int ret;
    ret = acl.hashCode();
    result = 37*result + ret;
    ret = stat.hashCode();
    result = 37*result + ret;
    return result;
  }
  public static String signature() {
    return "LGetACLResponse([LACL(iLId(ss))]LStat(lllliiiliil))";
  }
}
